teste

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -22,7 +22,6 @@ jobs:
       SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
       DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
       DBT_PROJECT_DIR: ${{ vars.DBT_PROJECT_DIR }}
-      GCLOUD_STORAGE_PATH_MANIFEST: ${{ vars.GCLOUD_STORAGE_PATH_MANIFEST }}
     
     steps:
 
@@ -49,7 +48,7 @@ jobs:
 
       - name: Copy manifest.json from Google Cloud Storage
         run: |
-          gsutil cp gs://$GCLOUD_STORAGE_PATH_MANIFEST/manifest.json . || echo "Manifest not found"
+          gsutil cp gs://${{ vars.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json . || echo "Manifest not found"
 
       - name: Install Dependencies
         run: pip install -r requirements.txt
